# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stepbystepGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1216, 586)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.StructDetailBtn = QtWidgets.QPushButton(self.widget)
        self.StructDetailBtn.setObjectName("StructDetailBtn")
        self.gridLayout_2.addWidget(self.StructDetailBtn, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.SBSstructureWidget = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SBSstructureWidget.sizePolicy().hasHeightForWidth())
        self.SBSstructureWidget.setSizePolicy(sizePolicy)
        self.SBSstructureWidget.setObjectName("SBSstructureWidget")
        self.gridLayout_2.addWidget(self.SBSstructureWidget, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.TLCDdetailBtn = QtWidgets.QPushButton(self.widget_2)
        self.TLCDdetailBtn.setObjectName("TLCDdetailBtn")
        self.gridLayout_3.addWidget(self.TLCDdetailBtn, 2, 0, 1, 1)
        self.SBSTLCDWidget = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SBSTLCDWidget.sizePolicy().hasHeightForWidth())
        self.SBSTLCDWidget.setSizePolicy(sizePolicy)
        self.SBSTLCDWidget.setObjectName("SBSTLCDWidget")
        self.gridLayout_3.addWidget(self.SBSTLCDWidget, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.splitter)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.ExcitationDetailBtn = QtWidgets.QPushButton(self.widget_3)
        self.ExcitationDetailBtn.setObjectName("ExcitationDetailBtn")
        self.gridLayout_4.addWidget(self.ExcitationDetailBtn, 2, 0, 1, 1)
        self.SBSexcitationWidget = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SBSexcitationWidget.sizePolicy().hasHeightForWidth())
        self.SBSexcitationWidget.setSizePolicy(sizePolicy)
        self.SBSexcitationWidget.setObjectName("SBSexcitationWidget")
        self.gridLayout_4.addWidget(self.SBSexcitationWidget, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        self.refreshbtn = QtWidgets.QPushButton(self.tab)
        self.refreshbtn.setObjectName("refreshbtn")
        self.gridLayout_5.addWidget(self.refreshbtn, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_3)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.widget_6 = QtWidgets.QWidget(self.splitter_3)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.equationFigureLabel = QtWidgets.QLabel(self.widget_6)
        self.equationFigureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.equationFigureLabel.setObjectName("equationFigureLabel")
        self.gridLayout_10.addWidget(self.equationFigureLabel, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.splitter_3)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_8 = QtWidgets.QLabel(self.widget_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 1)
        self.equationLineComboBox = QtWidgets.QComboBox(self.widget_5)
        self.equationLineComboBox.setObjectName("equationLineComboBox")
        self.gridLayout_7.addWidget(self.equationLineComboBox, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.equationTypeComboBox = QtWidgets.QComboBox(self.widget_5)
        self.equationTypeComboBox.setObjectName("equationTypeComboBox")
        self.equationTypeComboBox.addItem("")
        self.equationTypeComboBox.addItem("")
        self.gridLayout_7.addWidget(self.equationTypeComboBox, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 2, 1, 1, 1)
        self.equationWidget = QtWidgets.QWidget(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equationWidget.sizePolicy().hasHeightForWidth())
        self.equationWidget.setSizePolicy(sizePolicy)
        self.equationWidget.setObjectName("equationWidget")
        self.gridLayout_7.addWidget(self.equationWidget, 0, 2, 3, 1)
        self.gridLayout_8.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_5)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_4 = QtWidgets.QWidget(self.splitter_2)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 0, 1, 1, 1)
        self.outputsDOF2 = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsDOF2.sizePolicy().hasHeightForWidth())
        self.outputsDOF2.setSizePolicy(sizePolicy)
        self.outputsDOF2.setObjectName("outputsDOF2")
        self.outputsDOF2.addItem("")
        self.gridLayout_9.addWidget(self.outputsDOF2, 2, 0, 1, 1)
        self.outputsXaxis1 = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsXaxis1.sizePolicy().hasHeightForWidth())
        self.outputsXaxis1.setSizePolicy(sizePolicy)
        self.outputsXaxis1.setObjectName("outputsXaxis1")
        self.outputsXaxis1.addItem("")
        self.outputsXaxis1.addItem("")
        self.outputsXaxis1.addItem("")
        self.outputsXaxis1.addItem("")
        self.outputsXaxis1.addItem("")
        self.outputsXaxis1.addItem("")
        self.gridLayout_9.addWidget(self.outputsXaxis1, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 2, 1, 1)
        self.outputsDOF1 = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsDOF1.sizePolicy().hasHeightForWidth())
        self.outputsDOF1.setSizePolicy(sizePolicy)
        self.outputsDOF1.setObjectName("outputsDOF1")
        self.gridLayout_9.addWidget(self.outputsDOF1, 1, 0, 1, 1)
        self.outputsYaxis1 = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsYaxis1.sizePolicy().hasHeightForWidth())
        self.outputsYaxis1.setSizePolicy(sizePolicy)
        self.outputsYaxis1.setObjectName("outputsYaxis1")
        self.outputsYaxis1.addItem("")
        self.outputsYaxis1.addItem("")
        self.outputsYaxis1.addItem("")
        self.outputsYaxis1.addItem("")
        self.outputsYaxis1.addItem("")
        self.gridLayout_9.addWidget(self.outputsYaxis1, 1, 2, 1, 1)
        self.outputsXaxis3 = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsXaxis3.sizePolicy().hasHeightForWidth())
        self.outputsXaxis3.setSizePolicy(sizePolicy)
        self.outputsXaxis3.setObjectName("outputsXaxis3")
        self.outputsXaxis3.addItem("")
        self.outputsXaxis3.addItem("")
        self.outputsXaxis3.addItem("")
        self.outputsXaxis3.addItem("")
        self.outputsXaxis3.addItem("")
        self.outputsXaxis3.addItem("")
        self.gridLayout_9.addWidget(self.outputsXaxis3, 3, 1, 1, 1)
        self.outputsYaxis3 = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsYaxis3.sizePolicy().hasHeightForWidth())
        self.outputsYaxis3.setSizePolicy(sizePolicy)
        self.outputsYaxis3.setObjectName("outputsYaxis3")
        self.outputsYaxis3.addItem("")
        self.outputsYaxis3.addItem("")
        self.outputsYaxis3.addItem("")
        self.outputsYaxis3.addItem("")
        self.outputsYaxis3.addItem("")
        self.gridLayout_9.addWidget(self.outputsYaxis3, 3, 2, 1, 1)
        self.outputsYaxis2 = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsYaxis2.sizePolicy().hasHeightForWidth())
        self.outputsYaxis2.setSizePolicy(sizePolicy)
        self.outputsYaxis2.setObjectName("outputsYaxis2")
        self.outputsYaxis2.addItem("")
        self.outputsYaxis2.addItem("")
        self.outputsYaxis2.addItem("")
        self.outputsYaxis2.addItem("")
        self.outputsYaxis2.addItem("")
        self.gridLayout_9.addWidget(self.outputsYaxis2, 2, 2, 1, 1)
        self.outputsDOF3 = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsDOF3.sizePolicy().hasHeightForWidth())
        self.outputsDOF3.setSizePolicy(sizePolicy)
        self.outputsDOF3.setObjectName("outputsDOF3")
        self.outputsDOF3.addItem("")
        self.gridLayout_9.addWidget(self.outputsDOF3, 3, 0, 1, 1)
        self.outputsXaxis2 = QtWidgets.QComboBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputsXaxis2.sizePolicy().hasHeightForWidth())
        self.outputsXaxis2.setSizePolicy(sizePolicy)
        self.outputsXaxis2.setObjectName("outputsXaxis2")
        self.outputsXaxis2.addItem("")
        self.outputsXaxis2.addItem("")
        self.outputsXaxis2.addItem("")
        self.outputsXaxis2.addItem("")
        self.outputsXaxis2.addItem("")
        self.outputsXaxis2.addItem("")
        self.gridLayout_9.addWidget(self.outputsXaxis2, 2, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_9.addWidget(self.textBrowser, 4, 0, 1, 3)
        self.plotButton = QtWidgets.QPushButton(self.widget_4)
        self.plotButton.setObjectName("plotButton")
        self.gridLayout_9.addWidget(self.plotButton, 5, 2, 1, 1)
        self.outputPlt1 = QtWidgets.QWidget(self.splitter_2)
        self.outputPlt1.setMinimumSize(QtCore.QSize(800, 0))
        self.outputPlt1.setBaseSize(QtCore.QSize(0, 0))
        self.outputPlt1.setObjectName("outputPlt1")
        self.gridLayout_6.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.outputsYaxis3.setCurrentIndex(2)
        self.outputsYaxis2.setCurrentIndex(1)
        self.outputsXaxis1.currentIndexChanged['int'].connect(self.outputsXaxis2.setCurrentIndex)
        self.outputsXaxis1.currentIndexChanged['int'].connect(self.outputsXaxis3.setCurrentIndex)
        self.outputsXaxis2.currentIndexChanged['int'].connect(self.outputsXaxis1.setCurrentIndex)
        self.outputsXaxis3.currentIndexChanged['int'].connect(self.outputsXaxis1.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Step-By-Step Mode"))
        self.StructDetailBtn.setText(_translate("MainWindow", "Details"))
        self.label.setText(_translate("MainWindow", "Structure"))
        self.label_2.setText(_translate("MainWindow", "TLCD"))
        self.TLCDdetailBtn.setText(_translate("MainWindow", "Details"))
        self.label_3.setText(_translate("MainWindow", "Excitation"))
        self.ExcitationDetailBtn.setText(_translate("MainWindow", "Details"))
        self.refreshbtn.setText(_translate("MainWindow", "Load Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Inputs Summary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Assembly"))
        self.equationFigureLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Equation Type"))
        self.label_7.setText(_translate("MainWindow", "Equation Line"))
        self.equationTypeComboBox.setItemText(0, _translate("MainWindow", "Symbolic"))
        self.equationTypeComboBox.setItemText(1, _translate("MainWindow", "Numeric"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Equation of Motion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Solution"))
        self.label_4.setText(_translate("MainWindow", "DOF"))
        self.label_5.setText(_translate("MainWindow", "x-axis"))
        self.outputsDOF2.setItemText(0, _translate("MainWindow", "None"))
        self.outputsXaxis1.setItemText(0, _translate("MainWindow", "Time"))
        self.outputsXaxis1.setItemText(1, _translate("MainWindow", "Displacement"))
        self.outputsXaxis1.setItemText(2, _translate("MainWindow", "Velocity"))
        self.outputsXaxis1.setItemText(3, _translate("MainWindow", "Acceleration"))
        self.outputsXaxis1.setItemText(4, _translate("MainWindow", "Force"))
        self.outputsXaxis1.setItemText(5, _translate("MainWindow", "Excitation Acceleration"))
        self.label_6.setText(_translate("MainWindow", "y-axis"))
        self.outputsYaxis1.setItemText(0, _translate("MainWindow", "Displacement"))
        self.outputsYaxis1.setItemText(1, _translate("MainWindow", "Velocity"))
        self.outputsYaxis1.setItemText(2, _translate("MainWindow", "Acceleration"))
        self.outputsYaxis1.setItemText(3, _translate("MainWindow", "Force"))
        self.outputsYaxis1.setItemText(4, _translate("MainWindow", "Excitation Acceleration"))
        self.outputsXaxis3.setItemText(0, _translate("MainWindow", "Time"))
        self.outputsXaxis3.setItemText(1, _translate("MainWindow", "Displacement"))
        self.outputsXaxis3.setItemText(2, _translate("MainWindow", "Velocity"))
        self.outputsXaxis3.setItemText(3, _translate("MainWindow", "Acceleration"))
        self.outputsXaxis3.setItemText(4, _translate("MainWindow", "Force"))
        self.outputsXaxis3.setItemText(5, _translate("MainWindow", "Excitation Acceleration"))
        self.outputsYaxis3.setItemText(0, _translate("MainWindow", "Displacement"))
        self.outputsYaxis3.setItemText(1, _translate("MainWindow", "Velocity"))
        self.outputsYaxis3.setItemText(2, _translate("MainWindow", "Acceleration"))
        self.outputsYaxis3.setItemText(3, _translate("MainWindow", "Force"))
        self.outputsYaxis3.setItemText(4, _translate("MainWindow", "Excitation Acceleration"))
        self.outputsYaxis2.setItemText(0, _translate("MainWindow", "Displacement"))
        self.outputsYaxis2.setItemText(1, _translate("MainWindow", "Velocity"))
        self.outputsYaxis2.setItemText(2, _translate("MainWindow", "Acceleration"))
        self.outputsYaxis2.setItemText(3, _translate("MainWindow", "Force"))
        self.outputsYaxis2.setItemText(4, _translate("MainWindow", "Excitation Acceleration"))
        self.outputsDOF3.setItemText(0, _translate("MainWindow", "None"))
        self.outputsXaxis2.setItemText(0, _translate("MainWindow", "Time"))
        self.outputsXaxis2.setItemText(1, _translate("MainWindow", "Displacement"))
        self.outputsXaxis2.setItemText(2, _translate("MainWindow", "Velocity"))
        self.outputsXaxis2.setItemText(3, _translate("MainWindow", "Acceleration"))
        self.outputsXaxis2.setItemText(4, _translate("MainWindow", "Force"))
        self.outputsXaxis2.setItemText(5, _translate("MainWindow", "Excitation Acceleration"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Outputs"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

